### ISSUE TITLE
Website elements overlay dropzones

### ISSUE THREAD

**Issue by Gitoffthelawn** [andy-portmen/drag-and-dropzones#12]
Not sure if this is a simple z-index issue, or something more complicated.

On some websites, certain elements may overlay the dropzones.

For examples, see:
http://www.computerworld.com/article/3023533/microsoft-windows/microsoft-support-windows-10-new-hardware-itbwcw.html

**Comment by andy-portmen** [comment]
Seems like it was the `z-index` issue. Now the extension uses the maximum possible integer number for `z-index`. 

https://github.com/andy-portmen/drag-and-dropzones/blob/master/ddzones.xpi?raw=true

**Comment by Gitoffthelawn** [comment]
Glad it was that simple... I had a hunch.  Thanks for the update.  Will you be pushing it to AMO?

**Comment by andy-portmen** [comment]
The new version is submitted to AMO for review.

**Comment by Gitoffthelawn** [comment]
Thanks Andy! :-)
