### ISSUE TITLE
Minor bug: Grid dislocation in Settings

### ISSUE THREAD

**Issue by yfdyh000** [andy-portmen/drag-and-dropzones#4]
![Screenshot](https://cloud.githubusercontent.com/assets/1769875/11955858/6aac5d2e-a8f0-11e5-881d-055b1225f293.png)

**Comment by andy-portmen** [comment]
Please try the latest dev and confirm the fix
https://github.com/andy-portmen/drag-and-dropzones/blob/master/ddzones.xpi?raw=true

**Comment by yfdyh000** [comment]
The problem has been fixed, but the commit cause the entire window larger, slightly more than the visual height of 1366 \* 768 while Windows Taskbar placed at the bottom.

**Comment by andy-portmen** [comment]
I see, for the release version I decreased the height of each zone a bit.
