### ISSUE TITLE
A small suggestion about the translation

### ISSUE THREAD

**Issue by fheofff** [andy-portmen/drag-and-dropzones#6]
The Chinese translation by @yfdyh000 is very good. 

I have a small suggstion. I personally think that in <!ENTITY dendzones.settings.cmitems "Context menu actions">, the "Context menu actions" might be better translated as "右键菜单操作". It's just a small suggestion for you to consider. Thank you, yfdyh000!

**Comment by yfdyh000** [comment]
Hi, thank you for pointing this out.
I am hesitant which is better, so I don't mind if you submit a patch to it.

**Comment by fheofff** [comment]
Hi yfdyh000,
Thank you for your reply. I'm sorry. I don't know much about programming so I'm not sure how to do this. It's just a small suggestion for you to consider. If you think it's necessary, could you please add it? Thanks a lot. And I'm sorry since my suggesting like this might appear a bit impolite. I hope you don't mind. Thank you!

Best wishes!

**Comment by yfdyh000** [comment]
I really don't mind, but also don't think it is necessary.
It is a swing of balance for me, I have reasons to support either one separately.

If you willing, you can email me for further discussion using Chinese.
My emaill on https://github.com/yfdyh000.
