### ISSUE TITLE
"Save image as" context menu action error

### ISSUE THREAD

**Issue by Beerbear71** [andy-portmen/drag-and-dropzones#7]
The "Save image as" context menu not open the dialog windows instead of open full screen picture in same window above Firefox 40 version.

**Comment by yfdyh000** [comment]
I reproduce it sometimes on Fx43.

**Comment by andy-portmen** [comment]
Please share a webpage that we can reproduce this bug

**Comment by Beerbear71** [comment]
For example hvg.hu or facebook.com. I made a video to show it: https://goo.gl/photos/WWAXz7xqAsyUzDth9

**Comment by andy-portmen** [comment]
@Beerbear71 can you confirm the fix on 
https://github.com/andy-portmen/drag-and-dropzones/blob/master/ddzones.xpi?raw=true

Download the XPI and drop it into your Firefox browser.

**Comment by Beerbear71** [comment]
This is working perfectly. Thanks.
